# Generated by Django 4.0.2 on 2022-02-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welapp', '0004_category_alter_welmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welmodel',
            name='category',
            field=models.CharField(choices=[('KT', 'Kitchen'), ('BT', 'Bath'), ('RM', 'Room'), ('CO', 'Cook'), ('AM', 'Amenity'), ('OT', 'Other')], default='KT', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
